{ config, pkgs, ... }:
{
  environment = {
    systemPackages =
      with pkgs; [
        vim
      ];
  };

  nix.package = pkgs.nix;

  # Used for backwards compatibility, please read the changelog before changing.
  # $ darwin-rebuild changelog
  system.stateVersion = 4;

  users = {
    users.michael = {
      home = /Users/michael;
    };
  };

  homebrew = {
    enable = true;
    onActivation = {
      cleanup = "zap";
    };

    taps = [
      "adoptopenjdk/openjdk"
      "candid82/brew"
      "cloudflare/cloudflare"
      "cormacrelf/tap"
      "crowdin/crowdin"
      "cube2222/octosql"
      "danvergara/tools"
      "datawire/blackbird"
      "denisidoro/tools"
      "dnote/dnote"
      "dopplerhq/cli"
      "federico-terzi/espanso"
      "fsouza/prettierd"
      "github/gh"
      "hashicorp/tap"
      "heroku/brew"
      "homebrew-ffmpeg/ffmpeg"
      "homebrew/bundle"
      "homebrew/cask"
      "homebrew/cask-fonts"
      "homebrew/cask-versions"
      "homebrew/core"
      "homebrew/services"
      "huytd/cask-fonts"
      "jesseduffield/lazydocker"
      "koekeishiya/formulae"
      "mongodb/brew"
      "muesli/tap"
      "nicoverbruggen/cask"
      "noborus/tap"
      "pokanop/pokanop"
      "railwaycat/emacsmacport"
      "rigellute/tap"
      "roots/tap"
      "sachaos/todoist"
      "shivammathur/php"
      "sscotth/monoid"
      "superfly/tap"
      "teamookla/speedtest"
      "universal-ctags/universal-ctags"
      "xwmx/taps"
      "ycd/tap"
      "yqrashawn/goku"
      "zyedidia/literate"
    ];
    brews = [
      "libyaml"
      "python@3.11"
      "ansible"
      "boost"
      "asciidoc"
      {
        name = "berkeley-db";
        link = true;
      }
      "asciiquarium"
      "automake"
      "coreutils"
      "asdf"
      "bat"
      "bluetoothconnector"
      "bmon"
      "boxes"
      "broot"
      "gcc"
      "btop"
      "ghc"
      "cabal-install"
      "glib"
      "cairo"
      "ccat"
      "dialog"
      "certbot"
      "cheat"
      "chezmoi"
      "circleci"
      "cliclick"
      "cmake"
      "cmatrix"
      "cocoapods"
      "colormake"
      {
        name = "php";
        restart_service = true;
      }
      "composer"
      "ddgr"
      "deno"
      "diff-so-fancy"
      "difftastic"
      "dive"
      "dnsmasq"
      "docker-clean"
      "docker-compose"
      "docutils"
      "dtach"
      "duf"
      "duti"
      "folly"
      "edencommon"
      "editorconfig"
      "enchant"
      "exa"
      "exercism"
      "expat"
      "fizz"
      "wangle"
      "fbthrift"
      "fb303"
      "fd"
      "harfbuzz"
      "leptonica"
      "libass"
      "libbluray"
      "pango"
      "srt"
      "tesseract"
      "ffmpeg"
      "figlet"
      "fish"
      "fisher"
      "fortune"
      "fpp"
      "fselect"
      "fswatch"
      "fx"
      "gawk"
      "gdk-pixbuf"
      "gdrive"
      "ghostscript"
      "gifsicle"
      "gist"
      "git-delta"
      "git-filter-repo"
      "git-flow-avh"
      "git-lfs"
      "git-quick-stats"
      "git-secrets"
      "gitleaks"
      "glances"
      "global"
      "glow"
      "gnupg"
      "gpgme"
      "gmime"
      "go"
      "pkg-config"
      "gobject-introspection"
      "gpg-tui"
      "graphicsmagick"
      "netpbm"
      "librsvg"
      "graphviz"
      "grep"
      "grip"
      "guile"
      "gum"
      "helix"
      "htop"
      "httpie"
      "hugo"
      "icdiff"
      "iftop"
      "shared-mime-info"
      "libheif"
      "libraw"
      "imagemagick"
      "imlib2"
      "inetutils"
      "ispell"
      "jpegoptim"
      "jq"
      "just"
      "khard"
      "kubectx"
      "lazydocker"
      "lefthook"
      "less"
      "lftp"
      "libcaca"
      "libmng"
      "libraqm"
      "linode-cli"
      "llvm"
      "lua-language-server"
      "lua@5.1"
      "luarocks"
      "mailhog"
      "mailutils"
      "make"
      "mas"
      "mdcat"
      "mdv"
      "mkcert"
      "mmv"
      "moreutils"
      "mosh"
      "msmtp"
      "xapian"
      "mu"
      "multimarkdown"
      "mycli"
      "navi"
      "pandoc"
      "tig"
      "nb"
      "neofetch"
      "neomutt"
      "newsboat"
      "nghttp2"
      "nginx"
      "node"
      "node-build"
      "nodenv"
      "noti"
      "onefetch"
      "pkcs11-helper"
      {
        name = "openvpn";
        restart_service = true;
      }
      "optipng"
      "ossp-uuid"
      "overmind"
      "p7zip"
      "pass"
      "peco"
      "pgcli"
      "pillow"
      "pinentry-mac"
      "png2ico"
      "pngquant"
      "poppler"
      "postgresql@14"
      "pspg"
      "pstree"
      "psysh"
      "python@3.10"
      "python@3.8"
      "python@3.9"
      "reattach-to-user-namespace"
      "redis"
      "remind"
      "rename"
      "renameutils"
      "ripgrep-all"
      "rlwrap"
      "roswell"
      "ruby@3.0"
      "rust"
      "s3cmd"
      "selene"
      "shellcheck"
      "sk"
      "skaffold"
      "sphinx-doc"
      "sslmate"
      "starship"
      "stern"
      "subversion"
      "supervisor"
      "surfraw"
      "svgo"
      "task"
      "taskd"
      "tasksh"
      "taskwarrior-tui"
      "texinfo"
      "the_silver_searcher"
      "thefuck"
      "timewarrior"
      "timg"
      "tldr"
      "tmuxp"
      "toilet"
      "toot"
      "topgrade"
      "trash"
      "travis"
      "tty-clock"
      "ugit"
      "um"
      "urlview"
      "vdirsyncer"
      "vercel-cli"
      "viddy"
      "vifm"
      "vimpager"
      "virtualenv"
      "viu"
      "vtclock"
      "watch"
      "watchexec"
      "watchman"
      "watson"
      "wget"
      "woff2"
      "wp-cli"
      "wtfutil"
      "yadm"
      "yarn"
      "yq"
      "zellij"
      "zlib"
      "cloudflare/cloudflare/cloudflared"
      "cormacrelf/tap/dark-notify"
      "cube2222/octosql/octosql"
      "danvergara/tools/dblab"
      "dopplerhq/cli/doppler"
      "fsouza/prettierd/prettierd"
      "hashicorp/tap/packer"
      "heroku/brew/heroku"
      "noborus/tap/ov"
      "pokanop/pokanop/nostromo"
      "roots/tap/trellis-cli"
      "teamookla/speedtest/speedtest"
      "ycd/tap/dstp"
    ];
    casks = [
      "1password-cli"
      "chromedriver"
      "dash"
      "discord"
      "figma"
      "font-cascadia-code"
      "font-dm-mono"
      "font-et-book"
      "font-hasklig"
      "font-ibm-plex"
      "font-inter"
      "font-jetbrains-mono"
      "font-lilex"
      "font-meslo-for-powerline"
      "font-new-york"
      "font-nova-mono"
      "font-sf-compact"
      "font-sf-mono"
      "font-sf-mono-for-powerline"
      "font-sf-pro"
      "font-source-code-pro"
      "font-victor-mono"
      "google-chrome"
      "gpg-suite"
      "hashicorp-vagrant"
      "helo"
      "httpie"
      "image2icon"
      "iterm2"
      "kaleidoscope"
      "karabiner-elements"
      "keybase"
      "kindle"
      "kitty"
      "lando"
      "loom"
      "microsoft-auto-update"
      "ngrok"
      "nordvpn"
      "openvpn-connect"
      "parallels"
      "parallels-virtualization-sdk"
      "pgadmin4"
      "phpmon"
      "ray"
      "slack"
      "spotify"
      "telegram"
      "the-unarchiver"
      "tinkerwell"
      "transmit"
      "vagrant-vmware-utility"
      "virtualbox-beta"
      "visual-studio-code"
      "vmware-fusion"
      "whatsapp"
      "zoom"
    ];
    masApps = {
      "2048 Game" = 871033113;
      "Asphalt 8+" = 1563005359;
      "Bear" = 1091189122;
      "Beyond Blue" = 1466830870;
      "Builder's Journey" = 1466965366;
      "Calendar 366 II" = 1265895169;
      "Castle Crumble" = 1616814625;
      "CookingMama Cuisine" = 1563901930;
      "Developer" = 640199958;
      "Farm It!" = 1538476446;
      "GarageBand" = 682658836;
      "Ground News" = 1324203419;
      "Hogwash" = 1476082027;
      "Hyperspace Desktop" = 1454139710;
      "iMovie" = 408981434;
      "Keynote" = 409183694;
      "Kindle" = 405399194;
      "lumen." = 1489903517;
      "Messenger" = 1480068668;
      "Microsoft Excel" = 462058435;
      "Microsoft Word" = 462054704;
      "Numbers" = 409203825;
      "Octotree" = 1457450145;
      "Pages" = 409201541;
      "Patty Pursuit" = 1485030412;
      "Pixelmator Pro" = 1289583905;
      "stitch." = 1581052096;
      "Surfshark" = 1437809329;
      "Talon" = 1492913323;
      "Tureng" = 854063979;
    };
  };

  programs = {
    zsh.enable = true;
  };

  services = {
    nix-daemon.enable = true;
    karabiner-elements.enable = true;
  };
}
